name: Continuous publish
on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "pom.xml"
      - "resources/*"
      - "!resources/*.sha256"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "pom.xml"
      - "resources/*"
      - "!resources/*.sha256"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
  workflow_dispatch:


defaults:
  run:
    shell: bash


permissions:
  contents: read
  checks: write


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build
        run: mvn -B -V -e -ntp -Dstyle.color=always clean package

      - name: Write test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ success() || failure() }}
        with:
          report_paths: './build/test-results/test/TEST-*.xml'
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report on ${{ matrix.os }} (Ref ${{ github.ref }})
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - name: JaCoCo Code Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage (${{ matrix.os }})
          coverage_report_title: JaCoCo (${{ matrix.os }})
          fail_below_threshold: false
          publish_only_summary: true

      - name: Publish package
        run: mvn -B -V -e -ntp -Dstyle.color=always deploy
        if: ${{ (github.ref_name == 'master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')) && matrix.os == 'ubuntu-latest' }}
        env:
          COLOSSEUM_MAVEN_URL: ${{ secrets.COLOSSEUM_MAVEN }}
          COLOSSEUM_MAVEN_USERNAME: ${{ secrets.COLOSSEUM_MAVEN_USERNAME }}
          COLOSSEUM_MAVEN_PASSWORD: ${{ secrets.COLOSSEUM_MAVEN_PASSWORD }}
