name: Continuous publish
on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "pom.xml"
      - "resources/*"
      - "!resources/*.sha256"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/main/kotlin/**/*.kt"
      - "src/test/java/**/*.java"
      - "src/test/kotlin/**/*.kt"
      - "pom.xml"
      - "resources/*"
      - "!resources/*.sha256"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
  workflow_dispatch:


defaults:
  run:
    shell: bash


permissions:
  contents: read
  checks: write


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: corretto
          cache: "maven"

      - name: Build
        run: mvn -B -V -e -ntp -Dstyle.color=always clean verify

      - name: Write test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ success() || failure() }}
        with:
          report_paths: ./target/surefire-reports/TEST-*.xml
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report (${{ matrix.os }})
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - name: JaCoCo Code Coverage Report
        uses: NorthRealm/jacoco-csv-summary@v1.0.0
        with:
          csv-file: target/jacoco-report/jacoco.csv

      - name: Release
        id: release
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mvn_project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "$mvn_project_version"
          if [[ "$mvn_project_version" == *-SNAPSHOT ]]; then
            echo "snapshot=true" >> $GITHUB_OUTPUT
            echo "Snapshot"
          else
            echo "snapshot=false" >> $GITHUB_OUTPUT
            echo "Release"
          fi

      - name: Publish package
        run: ./_publish.sh
        if: ${{ matrix.os == 'ubuntu-latest' && github.ref_name == 'master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' && steps.release.outputs.snapshot == 'true') }}
        env:
          COLOSSEUM_MAVEN_URL: ${{ steps.release.outputs.snapshot == 'true' && secrets.COLOSSEUM_MAVEN || secrets.COLOSSEUM_MAVEN_RELEASE }}
          COLOSSEUM_MAVEN_USERNAME: ${{ secrets.COLOSSEUM_MAVEN_USERNAME }}
          COLOSSEUM_MAVEN_PASSWORD: ${{ secrets.COLOSSEUM_MAVEN_PASSWORD }}
